### ISSUE TITLE
Add coala for linting and fixing code

### ISSUE THREAD

**Issue by srisankethu** [vitelabs/vite-wallet#1]
Instead of downloading language specific linters, we can use [coala](https://coala.io/#/home) for linting and fixing for all languages. If my issue is accepted, I can set up a .coafile for every repo where it is needed(please specific in which repos do you need it). In a new issue, i will fix the linting errors is any arise.

Label: enhancement

I can here via the Vite developer initiative plan announced on Vite Announcement(Telegram).
ETH address: 0x08ac6d7ce02e7CFa050eECa4aFF73B862B6889bB

**Comment by soliury** [comment]
Is there any advantage of using coala? I think in front-end using eslint is enough. Can you explain why coala is better than eslint in front-end?

**Comment by soliury** [comment]
Through consideration, we think eslint is better for this project because this project is only a front-end project(vite-wallet). Eslint have the better support of Vue and Jsx.
Anyway, thank you very much.

**Comment by srisankethu** [comment]
@soliury  coala uses [ESLINT](https://github.com/coala/coala-bears/blob/master/bears/js/ESLintBear.py). It gives a multi-linter support too for [JS](https://github.com/coala/coala-bears/tree/master/bears/js).

I have just noticed https://github.com/vitelabs/vite-explorer-server and https://github.com/vitelabs/go-vite do not have [linters for Go Lang](https://github.com/coala/coala-bears/tree/master/bears/go).

**Comment by AllenLiuxt** [comment]
Thanks for the advice. The team believes at this stage eslint fits our web projects well and we don't want to introduce more complexity by involving more linters. As for golang linter you mentioned the built-in tools provided by the IDE and the language itself is sufficient as well.

**Comment by srisankethu** [comment]
@AllenLiuxt :+1:
